name: flutter_test_favbet
description: Test work.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 

  # State management
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  # Navigation
  go_router: ^14.8.1

  # HTTP client
  dio: ^5.8.0+1

  # JSON serialization
  json_annotation: ^4.9.0

  # Local storage
  shared_preferences: ^2.5.3

  # Dependency injection
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
